### ISSUE TITLE
求捐款排行榜

### ISSUE THREAD

**Issue by javthon** [ender-zhao/EZc#1]
没有排行榜没动力捐啊

**Comment by ender-zhao** [comment]
我会考虑做个历史捐赠名单的，但如果是捐赠排行榜，感觉捐赠的意义就变成了诱导捐赠

Tensorflow <notifications@github.com> 于 2021年2月22日周一 下午4:31写道：

**Comment by szkzn** [comment]
已微信捐赠20元，钱不多，第一次使用Clash，对汉化很满意哈，汉化方式简单粗暴替换文件，干净利落！希望能坚持下去，不要放弃了。
